---
- name: Configure EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      systemd:
        name: apache2
        state: started
        enabled: yes
